#!/bin/bash
# nh: a script to run a command detached from the terminal and wo output.

function usage() {
  echo "usage: $0 <command>"
  exit 1
}

[[ "$#" -lt "1" ]] && usage

nohup "$@" &> /dev/null & echo;
